import Footer from '@/components/Footer.jsx';
import Header from '@/components/Header.jsx';
import '../styles/App.css'


export const metadata = {
  title: "Movan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
