import '@/styles/App.css'
import { Providers } from './providers';
import { I18nProviderClient } from '../../locales/client';
import { ReactElement } from 'react';

export const metadata = {
  title: "Movan",
  description: "Generated by create next app",
};

export default function RootLayout({ params: { locale }, children }: { params: { locale: string }, children: ReactElement }) {
  return (
    <html lang="en" >
      <body>
        <Providers>
          <I18nProviderClient locale={locale}>
            {children}
          </I18nProviderClient>
        </Providers>
      </body>
    </html>
  );
}
