import '@/styles/App.css'


export const metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default function LoginLayout({ children }) {
  return (
    <div>
        {children}
    </div>
  );
}
